language: android
jdk: oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - tools
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Repos needed
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
      - 'intel-android-extra-license.+'
      - '.+'

jobs:
  include:
    - stage: Assemble
      script: ./gradlew assemble
    - stage: Unit Tests
      script: ./gradlew test