language: android
jdk: oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - tools
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Repos needed
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
      - 'intel-android-extra-license.+'
      - '.+'

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  # Compile the SDK
  - ./gradlew assemble

  # Run initTests
  - ./gradlew test